# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mGC_2zMwv1bRyqc7KHlQzDE_uyfClIDe
"""

#Calculator

def conversion():
  conv_inp = input("""Choose the conversion method.
  1. Kg to Lb
  2. Km to m
  3. Kg to g
  4. L to ml
  5. MB to KB\n\nYour Choice : """)
  if conv_inp == '1':
    first_value = float(input("Enter your first value in (Kg) : "))
    answer = first_value * 2.20462
    print(f"{first_value} Kgs -----> {answer} Lbs")
  elif conv_inp == '2':
    first_value = float(input("Enter your first value in (Km) : "))
    answer = first_value * 1000
    print(f"{first_value} Km -----> {answer} m")
  elif conv_inp == '3':
    first_value = float(input("Enter your first value in (Kg) : "))
    answer = first_value * 1000
    print(f"{first_value} Kgs -----> {answer} g")
  elif conv_inp =='4':
    first_value = float(input("Enter your first value in (L) : "))
    answer = first_value * 1000
    print(f"{first_value} Kgs -----> {answer} ml")
  elif conv_inp == '5':
    first_value = float(input("Enter your first value in (MB) : "))
    answer = first_value * 1000
    print(f"{first_value} Kgs -----> {answer} KB")
  else :
    print("Invalid Input")

import time
print("WELCOME TO SRIKAR's CALCULATOR!")
print()
while True:
  operation = input("""Choose which operation you want to proceed with:
  Use the numbers in bracket to proceed.
  1) (+) (ADD)ition
  2) (-) (SUB)traction
  3) (x) (MUL)tiplication
  4) (/) (DIV)ision
  5) (Conversion)
  6) (QUIT)
  7) (Feedback)
  8) (Credits)\n\nYour Choice : """)
  print()
  print()
  if operation == "6":
    print("Thankyou for using the calculator! The application will auto-exit after 10 seconds.")
    time.sleep(10)
    break
  elif operation == "5":
    conversion()
  elif operation == "7":
    player_feedback = int(input("How much would you rate this calculator?(1-10) "))
    print(f"\nYou gave the calculator {player_feedback}/10\n")
    if player_feedback >= 8:
      print(f"OMG! {player_feedback}! I'm Glad you found this helpful!")
    elif player_feedback >= 5 and player_feedback <8:
      print(f"{player_feedback}! I will try to improve this application for you!")
    elif player_feedback < 5:
      print(f"Oh really? A {player_feedback} ?! Code one yourself now >:)")
      time.sleep(5)
      break
  elif operation == "8":
    print("> Work Done by Srikar")
    time.sleep(1)
    print("> Time Taken : Probably 20 minutes")
    time.sleep(5)
    print("What else do you want?")
    time.sleep(3)
    print("Go use the calculator bruh!") 
  elif operation == "1":
    first_value = float(input("Enter the first value: "))
    second_value = float(input("Enter the second value: "))
    print(f"Your Desired answer is {first_value+second_value}")
  elif operation =="2":
    first_value = float(input("Enter the first value: "))
    second_value = float(input("Enter the second value: "))
    print(f"Your Desired answer is {first_value-second_value}")
  elif operation == "3":
    first_value = float(input("Enter the first value: "))
    second_value = float(input("Enter the second value: "))
    print(f"Your Desired answer is {first_value*second_value}")
  elif operation == "4":
    first_value = float(input("Enter the first value: "))
    second_value = float(input("Enter the second value: "))
    print(f"Your Desired answer is {first_value/second_value}")
  print()